### ISSUE TITLE
Freeze after booting

### ISSUE THREAD

**Issue by Iga44** [JamesIsWack/Akari-Legacy#1]
Hello.
I have a trouble after installing this plugin.
After starts , at  the user choose menu console  is stuck. And only way is reboot. Then begin boot again and at users menu select  console  get stuck.
So I can't get access to xmb

How could delete line "/dev_hdd0/plugins/Akari.sprx" from boot_plugins.txt or  file Akari.sprs itself now?

**Comment by kernaltrap8** [comment]
what is your firmware version, and what other plugins do you have enabled?

**Comment by Iga44** [comment]
rebug_4.80

No others plugins, except webman mod

**Comment by kernaltrap8** [comment]
yeah, update to at the very least 4.84, the plugin was developed on that firmware and is only supposed to work on 4.84 and above.

**Comment by Iga44** [comment]
Ok, if i didn't want update....  -  if I pull out the hard drive  and connect it with PC  - will it be recognized at windows to delete boot_plugins.txt?

**Comment by kernaltrap8** [comment]
no, you cant do that. the drive is encrypted. since you have webMAN MOD, what you can try doing is resetting the video settings, and once on the HDMI output screen, go to your PC and go to your PS3s IP address in your browser, and navigate to boot_plugins, and delete it.

**Comment by Iga44** [comment]
How could  reset  video settings? And i don't know ps3s IP cause it was disabled wifi...

So, the only way for my situation is update?

**Comment by kernaltrap8** [comment]
yeah, without networking you need to update. 
here are some firmwares to use:
[REBUG 4.84.2 REX (CEX)](https://archive.midnightchannel.net/SonyPS/Firmware/download/0835d81e3c581f3bdfdfbe86fca5e192/REBUG_CRC%5B67E4A95C%5D_FW%5Bv4.84.2_RE%5D_PS3UPDAT.PUP)
[REBUG 4.84.2 D-REX (DEX)](https://archive.midnightchannel.net/SonyPS/Firmware/download/9211252d41841461c6299bfad48fa7f1/REBUG_CRC%5B63F00899%5D_FW%5Bv4.84.2_RE%5D_PS3UPDAT.PUP)

**Comment by Iga44** [comment]
Ok, I see.
 thanks
